services:
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install Flask==2.3.3
      pip install yt-dlp==2023.12.30
      pip install Werkzeug==2.3.7
      pip install requests==2.31.0
      echo "=== BUILD COMPLETED ==="
      ls -la
      pwd
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
