services:
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python /opt/render/project/src/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
